### ISSUE TITLE
hint for incomplete output

### ISSUE THREAD

**Issue by BravoScarleth** [TobiTekath/DTUrtle#11]
Hi,
I did everything the bullets show and it worked fine.
I'm only concerned with how to get the transcripts that are significant, not just the list of transcripts, else the list with their respective p-value or q-value by transcript. 
Is it possible to know which specific transcripts by gene are significant after run DEG?

Thanks

**Comment by TobiTekath** [comment]
Hi @BravoScarleth, thank you for usign DTUrtle.

The significant transcripts as well as a table with gene and transcript multiple-testing adjusted p-values are available within your DTUrtle object, if you have the run the **DTU** analysis workflow.
If you have _only_ run the DGE analysis, only gene-level results can be provided.

You can easily check which results are available in your DTUrtle object:

```
# suppose my_obj is your dturtle object


# if you have performed a DGE analysis, the following object should be available
## within this object all DGE results are stored, including a table of the differentially expressed genes.
my_obj$dge_analysis


# if you have performed a DTU analysis, the following objects should be available

# contains a list of all genes which passed the omnibus-test signigicance threshold, i.e. showing a "interesting" overall transcript composition
my_obj$sig_gene

# contains a list of all specific transcripts of the above mentioned genes, which passed the DTU significance threshold.
my_obj$sig_tx

# a table of gene- and transcript-level adjusted p-values:
my_obj$FDR_table

# To get a nice table of just the significant transcripts and their adjusted p-values, you could do:
my_obj$FDR_table[match(my_obj$sig_tx, my_obj$FDR_table$txID), ]
```

I hope this answer resolves all your questions.

Best,
Tobias

**Comment by BravoScarleth** [comment]
Hi Tobias,

Thanks. it worked perfect.

Best, Scarleth
