### ISSUE TITLE
Map transcripts to gene clusters

### ISSUE THREAD

**Issue by gadepallivs** [TobiTekath/DTUrtle#13]
Hello, I'm using the KB output and then Kallisto-quant-TCC to quantify my transcripts. I would like to plot the gene clusters and overlay how the transcripts of interests are expressed across all the clusters. Or even a bar, plot that would quantify the expression of my transcript of interest across various cluster. How to approach this using the DTUrtle package ?
I tried using the Seurat package, but unable to identify the clusters based on the transcript ID. If these are gene IDs, it is easy to map and name the clusters. If I convert the transcript ID to gene names, it results in duplicate rownames. Any suggestion is appreciated

**Comment by TobiTekath** [comment]
Hi @gadepallivs,

thank you for reaching out and please excuse the very late reply.

I have to admit, that I can not completely follow your thoghts above. Could you provide me with some more information?

I assume you have single-cell RNAseq data and have already clustered the single cells and performed a dimensional reduction?
And now you want to create a plot of transcript expression across those clusters?

My initial ideas would be to either overlay the transcript expression fractions over a dim. reduction plot to see if any cluster stands out. Alternatively the barplot should be easy to create, just with the transcript quantification data (you would not necessarily need DTUrtle for that). Could you tell me which steps of the analysis you already performed?

Best,
Tobi
