### ISSUE TITLE
Further help needed with transcript mapping fonts

### ISSUE THREAD

**Issue by SianPiret** [TobiTekath/DTUrtle#18]
Hi - I'm still having a problem in which I get boxes instead of arrows when plotting the transcripts view, per issue #3.  I'm on mac OS 12.6.2, R 4.2.2, DTUrtle 1.0.2 

I used showtext to import Apple Symbol:

`font_add(family = "Apple_Symbol", regular = "/System/Library/Fonts/Apple Symbols.ttf")
showtext_auto()`
Then the lines you suggested in the earlier issue work perfectly:
`par(family = "Apple_Symbol")
plot(1:5, t = "n")
text(2,2,c(intToUtf8(c(11014))),cex=3)
text(4,4,c(intToUtf8(c(11015))),cex=3)`
To produce:
![AppleSymbolTest](https://github.com/TobiTekath/DTUrtle/assets/135169912/9132cf64-d632-4ba7-9a64-e9d8ac71055b)

But still when I then try it for the transcript view plotting, I still get the boxes:
`plot_transcripts_view(dturtle = dturtle, 
                      genes = "HEY1", 
                      gtf = "../gencode.v34.annotation.gtf", 
                      genome = 'hg38',
                      one_to_one = TRUE,
                      arrow_colors = c("#7CAE00", "#D30000"),
                      family="Apple_Symbol")`
![Transcript_view_eg](https://github.com/TobiTekath/DTUrtle/assets/135169912/09c1e954-568d-4710-ab2a-6fba45de1549)

Any further help appreciated!

> 
> Hi @lijinw ,
> 
> so we definitively found the culprit. To fix the issue, you must find a font supporting at least these two glyphs.
> 
> You could have a look at the [extrafont](https://cran.r-project.org/package=extrafont) or [showtext](https://cran.r-project.org/package=showtext) packages - these shall allow you to import additional fonts.
> 
> Again, you might try the "Apple Symbols" font that should be pre-installed on your system. At least according to Wikipedia it should support the needed Glyphs (see [here](https://en.wikipedia.org/wiki/Apple_Symbols)).
> 
> _Originally posted by @TobiTekath in https://github.com/TobiTekath/DTUrtle/issues/3#issuecomment-984548209_
>

**Comment by m-noonan** [comment]
Hi, related to this question, is there a way to increase the font size of the transcript name (ie HEY1-202)? I tried adding the 'pointsize' option in 'plot_transcripts_view' but it didn't seem to change the font size.

**Comment by TobiTekath** [comment]
@SianPiret Sorry, but as I do not have an Apple device, this problem is not easily debug-able for me. The font system under macOS seems to be a bit more complicated as I initially thought when deciding to include the arrows as UTF-8 symbols.

@m-noonan Please have a look at the thid value of the `fontsize_vec `. Increasing it to e.g. `c(10, 1.1, 0.9)` should increase the label font size.
