### ISSUE TITLE
barplot question

### ISSUE THREAD

**Issue by m-noonan** [TobiTekath/DTUrtle#19]
Hello,

Something on my barplot seems off, like there are lots of thin, spread out lines. Is this okay?

Also, where can I find the "proportions" (mean proportion fit per subgroup (red line value) information used for this plotting? 

![plot_zoom_png](https://github.com/TobiTekath/DTUrtle/assets/123900415/7e3051c0-ada9-4048-a71c-e802b53d7071)
![plot_zoom_png-2](https://github.com/TobiTekath/DTUrtle/assets/123900415/59126dbd-876e-49e7-83f9-7e8588a35b2a)

**Comment by TobiTekath** [comment]
Hi @m-noonan, I do not see an issue here. There should be one line for every cell / sample in your data - ordered by the fraction values of the first transcript on the left side of the plot.
If there is a "blank" line, either the expression fraction is 0 - or the cell / sample has in general no expression of that gene, and therefore no fractions at all.

Hope this makes the visualization more clear.

**Comment by m-noonan** [comment]
@TobiTekath Yes this helps, thank you! Is there some way to condense it? Also, in regards to my second question before, where can I find the "proportions" (mean proportion fit per subgroup (red line value) information used for this plotting?
