### ISSUE TITLE
How to import .mtx files?

### ISSUE THREAD

**Issue by vasikara17** [TobiTekath/DTUrtle#22]
Hello, 
thanks for the great tool! I am having trouble using the type of matrix I have since the method I am using for single cell is a bit different. 
The alignment is done with STAR and I have as an output a **DGE.mtx** file, which I use in Seurat analysis. Is it possible to use it as an input in your package?.

I have done the Seurat analysis and used the section in your vignette which says starting from the Seurat object but the combine_to_matrix should be done if I understood correctly. 

Do you have a suggestion on how to solve this?

Many thanks,
Vasiliki

**Comment by TobiTekath** [comment]
Hi @vasikara17,

you can surely use your gene-level(?) STAR counts with DTUrtle's DGE analysis - and if you already have the data imported into an Seurat object it is even easier.
Just provide the object to `run_deseq2()`, providing your seurat object as the `counts` parameter, and the Seurat objects `meta.data` table as `pd`.

Please make sure that the Seurat object's active.assay contains raw and unscaled count information  - most probably it should be the "RNA" assay.
