### ISSUE TITLE
Df is not dataframe error

### ISSUE THREAD

**Issue by pragathi-sneha** [TobiTekath/DTUrtle#23]
Dturtle <~ run_drimseq () 

gives an error 

it works fine till removing features and then gives an error : df is not a dataframe

Pls help me with this . TIA

**Comment by TobiTekath** [comment]
Hi Tia, thank you for using DTUrtle and reaching out.

I need a bit more information about the issue you are experiencing.

Could you please provide the error stack trace (which would allow to see where and in which line the error occurs).
Also any previous messages run_drimseq() gives, as well as an head of your tx2gene for example would help immensely.

Many thanks.
