### ISSUE TITLE
matrix of transcript counts

### ISSUE THREAD

**Issue by yoavhadas** [TobiTekath/DTUrtle#6]
Hello,
Is it possible to import a matrix of transcript counts as txt or csv file instead of raw data?

Thanks
Yoav

**Comment by TobiTekath** [comment]
Hi @yoavhadas ,

if you have a matrix file of counts, you can import it into R and directly plug it into the `run_deseq2()` or `run_drimseq()` functions.

Pease note that your data will not be scaled or normalized in any way by this approach though.

If you have a raw count file per sample, you could try the `import_counts()` function with `type="none"` and specify the columns with the data manually. Then an appropriate scaling should be applied.

Best,
Tobi

**Comment by yoavhadas** [comment]
Thank you Tobi
I will give it a try.

Yoav

**Comment by yoavhadas** [comment]
Hello again,
In my csv file, I have barcodes as columns and transcripts as rows:

TranscriptID,CCGCAGTCAGGACTCA,TCATACCACTTGAGTT,TGCGCGTTAATTACCA,AAGTAGAGTACTAAGT
Transcript1,0,0,0,0
Transcript2,0,0,0,0
Transcript3,0,0,3.93,0

 I can import it to R using read.csv("transcript_matrix.csv"); however, I am not sure what you mean by: "specify the columns with the data manually."

Any help will be appreciated.
Thanks
Yoav.
