### ISSUE TITLE
plot_transcripts_view with local genome file

### ISSUE THREAD

**Issue by anilthanki** [TobiTekath/DTUrtle#7]
A genome for organisms of interest is always not available on UCSC so it will be good to be able load local genome to be able to plot transcripts view.

**Comment by TobiTekath** [comment]
Hi @anilthanki,

please excuse the long response time. You are actually able to use the genome annotation of your choice and are not restricted to UCSC. The UCSC genome name is only used to fetch the appropriate ideograms.

If you set `genome=NULL` in `plot_transcripts_view()` it should work flawlessly.

Best,
Tobi
