### ISSUE TITLE
plot transcript view table

### ISSUE THREAD

**Issue by mavino** [TobiTekath/DTUrtle#8]
Hi there,
is there a way to get, after having run plot_transcripts_view() on my dturtle object, a table with all the values of the mean fitted proportional changes per transcript per gene?
Thanks a lot.

**Comment by TobiTekath** [comment]
HI @mavino,

if I understand your request correctly, you might want to call the internal `get_diff()` function. You can use it like this:
`DTUrtle:::get_diff("gene_of_interest", dturtle_object)`

The fitted proportions are computed in the `run_drimseq()` step, thus independently of the `plot_transcripts_view()` calls.

Hope that helps.
Best,
Tobi

**Comment by mavino** [comment]
great!! thanks a lot
